'use strict';
const {Cube,moves,rotate}=CubeEngine,cube=new Cube(),canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
let yaw=-.57,pitch=.43,zoom=1,w=0,h=0,polys=[],animation=null,drag=null,history=[],future=[],queue=[],elapsed=0,started=0,challenge=false,lastSolved=true;
const pointers=new Map();let pinch=null;
function camera(v){return rotate(rotate(v,1,yaw),0,pitch)}
function project(v){const q=camera(v),scale=Math.min(w*.19,h*.24)*zoom/(1-q[2]/12);return [w*.55+q[0]*scale,h*.56-q[1]*scale,q[2]]}
function path(points){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath()}
function inside(p,pts){let result=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])result=!result}return result}
function hit(p){return [...polys].reverse().find(f=>inside(p,f.points))}
function render(now){const rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
 if(animation&&!animation.manual){const t=Math.min(1,(now-animation.start)/animation.duration);animation.angle=animation.from+(animation.to-animation.from)*(1-Math.pow(1-t,3));if(t===1){const done=animation;animation=null;if(done.dir){cube.turn(done.axis,done.layer,done.dir);if(done.record){history.push([done.axis,done.layer,done.dir]);future=[]}}update();if(queue.length)animate(...queue.shift())}}
 const shadow=ctx.createRadialGradient(w*.55,h*.83,3,w*.55,h*.83,w*.28);shadow.addColorStop(0,'#52634525');shadow.addColorStop(1,'#52634500');ctx.fillStyle=shadow;ctx.save();ctx.translate(0,h*.83);ctx.scale(1,.22);ctx.translate(0,-h*.83);ctx.fillRect(0,0,w,h*5);ctx.restore();
 polys=[];for(const c of cube.cubies){const active=animation&&c.p[animation.axis]===animation.layer;const transform=v=>active?rotate(v,animation.axis,animation.angle):v;for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const n=[0,0,0];n[axis]=sign;const normal=transform(n);if(camera(normal)[2]<.05)continue;const u=(axis+1)%3,v=(axis+2)%3;const vertices=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>{let p=c.p.slice();p[axis]+=sign*.478;p[u]+=a*.452;p[v]+=b*.452;return project(transform(p))});const sticker=c.stickers.find(s=>s.n.every((x,i)=>x===n[i]));polys.push({points:vertices,z:vertices.reduce((a,p)=>a+p[2],0)/4,color:sticker?.color||'#293530',c,n,sticker:!!sticker})}}
 polys.sort((a,b)=>a.z-b.z);for(const f of polys){path(f.points);ctx.fillStyle='#293530';ctx.strokeStyle='#293530';ctx.lineWidth=5;ctx.lineJoin='round';ctx.fill();ctx.stroke();ctx.fillStyle=f.color;ctx.fill();ctx.strokeStyle='#ffffff20';ctx.lineWidth=1;ctx.stroke()}
 $('time').textContent=format(elapsed+(started?Date.now()-started:0));requestAnimationFrame(render)}
function format(ms){const s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function update(){const solved=cube.solved();$('steps').textContent=String(history.length).padStart(3,'0');$('undo').disabled=!history.length||!!animation||!!queue.length;$('redo').disabled=!future.length||!!animation||!!queue.length;$('status').textContent=queue.length?'打乱中':solved?'已复原':'探索中';if(solved&&challenge&&!lastSolved&&!queue.length){elapsed+=started?Date.now()-started:0;started=0;challenge=false;toast('恭喜复原！用时 '+format(elapsed))}lastSolved=solved}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),2300)}
function startTimer(){if(!started){started=Date.now();challenge=true}}
function animate(axis,layer,dir,record=true,duration=Number($('speed').value),from=0){animation={axis,layer,dir,record,start:performance.now(),duration,from,to:dir*Math.PI/2,angle:from};update()}
function move(name,inverse=false){if(animation||queue.length||pointers.size)return;startTimer();const [a,l,d]=moves[name];animate(a,l,d*(inverse?-1:1))}
function undo(){if(animation||queue.length||!history.length)return;const m=history.pop();future.push(m);animate(m[0],m[1],-m[2],false)}
function redo(){if(animation||queue.length||!future.length)return;startTimer();const m=future.pop();history.push(m);animate(...m,false)}
function reset(){animation=null;queue=[];drag=null;pinch=null;pointers.clear();cube.reset();history=[];future=[];elapsed=0;started=0;challenge=false;update()}
function resetView(){yaw=-.57;pitch=.43;zoom=1}
const names={U:'上层',D:'下层',L:'左层',R:'右层',F:'前层',B:'后层',M:'中竖层',E:'中横层',S:'中前层'};
for(const key of Object.keys(names)){const b=document.createElement('button');b.innerHTML=key+'<small>'+names[key]+'</small>';b.setAttribute('aria-label',names[key]+' '+key);let down=0;b.onpointerdown=()=>down=Date.now();b.onclick=e=>move(key,e.shiftKey||Date.now()-down>450);b.oncontextmenu=e=>{e.preventDefault();move(key,true)};$('controls').append(b)}
$('undo').onclick=undo;$('redo').onclick=redo;$('reset').onclick=()=>{reset();toast('魔方已复原，新的一局随时开始')};$('view').onclick=resetView;
$('scramble').onclick=()=>{reset();let prev='';const keys=['U','D','L','R','F','B'];for(let i=0;i<24;i++){let k;do{k=keys[Math.floor(Math.random()*6)]}while(k===prev);prev=k;const [a,l,d]=moves[k];queue.push([a,l,d*(Math.random()<.5?1:-1),false,65])}challenge=true;animate(...queue.shift());toast('打乱 24 步 · 转动后开始计时')};
$('speed').oninput=()=>{$('speedValue').textContent=Number($('speed').value)<250?'迅速':Number($('speed').value)>400?'舒缓':'标准'};
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='y'||e.shiftKey)redo();else undo();return}if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&moves[e.key.toUpperCase()]){e.preventDefault();move(e.key.toUpperCase(),e.shiftKey)}});
function point(e){const r=canvas.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top]}
canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.setPointerCapture(e.pointerId);const p=point(e);pointers.set(e.pointerId,p);if(pointers.size===2){if(animation?.manual)animation=null;drag=null;const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a[0]-b[0],a[1]-b[1]),center:[(a[0]+b[0])/2,(a[1]+b[1])/2]};return}if(pointers.size>2)return;const f=!animation&&hit(p);drag={start:p,last:p,face:f?.sticker?f:null,axis:null}};
canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const p=point(e);pointers.set(e.pointerId,p);if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()],distance=Math.hypot(a[0]-b[0],a[1]-b[1]),center=[(a[0]+b[0])/2,(a[1]+b[1])/2];zoom=Math.max(.6,Math.min(1.65,zoom*distance/Math.max(pinch.distance,1)));yaw+=(center[0]-pinch.center[0])*.008;pitch=Math.max(-1.3,Math.min(1.3,pitch+(center[1]-pinch.center[1])*.008));pinch={distance,center};return}if(!drag)return;const dx=p[0]-drag.start[0],dy=p[1]-drag.start[1];if(!drag.face){yaw+=(p[0]-drag.last[0])*.008;pitch=Math.max(-1.3,Math.min(1.3,pitch+(p[1]-drag.last[1])*.008));drag.last=p;return}if(drag.axis===null&&Math.hypot(dx,dy)>7){const f=drag.face,center=f.c.p.map((x,i)=>x+f.n[i]*.5),origin=project(center);let best=-1;for(let a=0;a<3;a++){if(f.n[a])continue;const target=project(rotate(center,a,.1)),t=[target[0]-origin[0],target[1]-origin[1]],len=Math.hypot(...t),score=Math.abs((dx*t[0]+dy*t[1])/len);if(score>best){best=score;drag.axis=a;drag.tangent=t.map(x=>x/len)}}animation={axis:drag.axis,layer:f.c.p[drag.axis],angle:0,manual:true}}
if(drag.axis!==null&&animation?.manual)animation.angle=Math.max(-Math.PI,Math.min(Math.PI,(dx*drag.tangent[0]+dy*drag.tangent[1])/ (Math.min(w,h)*.22)));};
function release(e,cancel=false){pointers.delete(e.pointerId);if(animation?.manual){const {axis,layer,angle}=animation;const dir=cancel?0:Math.abs(angle)>=Math.PI/4?Math.sign(angle):0;if(dir)startTimer();animate(axis,layer,dir,true,180,angle)}drag=null;if(pointers.size<2)pinch=null}
canvas.onpointerup=e=>release(e);canvas.onpointercancel=e=>release(e,true);canvas.onlostpointercapture=e=>{if(pointers.has(e.pointerId))release(e,true)};
canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.6,Math.min(1.65,zoom*Math.exp(-e.deltaY*.001)))};canvas.addEventListener('wheel',canvas.onwheel,{passive:false});canvas.onwheel=null;
canvas.ondblclick=e=>{if(!hit(point(e)))resetView()};let lastTap=0;canvas.addEventListener('pointerup',e=>{if(e.pointerType==='touch'&&!hit(point(e))){if(Date.now()-lastTap<300)resetView();lastTap=Date.now()}});
update();requestAnimationFrame(render);
