const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),noop=()=>{},context=new Proxy({createRadialGradient:()=>({addColorStop:noop})},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});
function element(){return {value:'300',classList:{add:noop,remove:noop},append:noop,setAttribute:noop,addEventListener:noop,getContext:()=>context,getBoundingClientRect:()=>({width:900,height:650,left:0,top:0}),setPointerCapture:noop}}
const canvas=element(),sandbox={CubeEngine:require('./engine.js'),document:{querySelector:()=>canvas,getElementById:id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id)},createElement:element,addEventListener:noop},devicePixelRatio:1,performance:{now:()=>0},Date,Math,setTimeout:()=>0,clearTimeout:noop,requestAnimationFrame:noop};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),sandbox);
function run(s){return vm.runInContext(s,sandbox)}
run('render(0)');assert.ok(run('polys.length')>0);run("move('R');render(1000)");assert.equal(run('history.length'),1);assert.equal(run('cube.solved()'),false);run('undo();render(1000)');assert.equal(run('cube.solved()'),true);assert.equal(run('future.length'),1);run('redo();render(1000)');assert.equal(run('cube.solved()'),false);run('reset()');assert.equal(run('history.length'),0);assert.equal(run('started'),0);
run("$('scramble').onclick();for(let i=0;i<25;i++)render(1000)");assert.equal(run('queue.length'),0);assert.equal(run('animation'),null);assert.equal(run('history.length'),0);assert.equal(run('started'),0);assert.equal(run('cube.solved()'),false);run("move('U');render(1000)");assert.ok(run('started')>0);
run('reset();render(0)');const p=run('(()=>{const f=[...polys].reverse().find(f=>f.sticker);return f.points.reduce((a,p)=>[a[0]+p[0]/4,a[1]+p[1]/4],[0,0])})()');canvas.onpointerdown({button:0,pointerId:1,clientX:p[0],clientY:p[1]});canvas.onpointermove({pointerId:1,clientX:p[0]+150,clientY:p[1]});assert.equal(run('animation.manual'),true);canvas.onpointerup({pointerId:1});run('render(1000)');assert.equal(run('history.length'),1);
console.log('App checks passed: rendering smoke test, move, undo, redo, reset, scramble, timer, surface drag');
